clean:
	@echo
	@echo "Cleaning..." 

copy: 
	@rm ./include/spp_incl -rf
	@-mkdir ./include/spp_incl
	@cp ../comm/report/report_handle.h ./include/spp_incl/.
	@cp ../comm/spp_version.h ./include/spp_incl/.
	@cp ../comm/serverbase.h ./include/spp_incl/.
	@cp ../comm/timerlist.h ./include/spp_incl/.
	@cp ../comm/exception.h ./include/spp_incl/.
	@cp ../comm/timestamp.h ./include/spp_incl/.
	@cp ../comm/myepoll.h ./include/spp_incl/.
	@cp ../comm/poller.h ./include/spp_incl/.
	@cp ../comm/tbase/atomic*.h ./include/spp_incl/.
	@cp ../comm/tbase/myatomic*.h ./include/spp_incl/.
	@cp ../comm/tbase/list.h ./include/spp_incl/.
	@cp ../comm/tbase/tcommu.h ./include/spp_incl/.
	@cp ../comm/tbase/tlog.h  ./include/spp_incl/.
	@cp ../comm/tbase/tprocmon.h  ./include/spp_incl/.
	@cp ../comm/tbase/tstat.h  ./include/spp_incl/.
	@cp ../comm/tbase/tstat_policy.h  ./include/spp_incl/.
	@cp ../async/asyn_api.h ./include/spp_incl/.
	@cp ../async/spp_async_interface.h ./include/spp_incl/.
	@cp ../async_frame/CommDef.h ./include/spp_incl/.
	@cp ../async_frame/AsyncFrame.h ./include/spp_incl/.
	@cp ../async_frame/IState.h ./include/spp_incl/.
	@cp ../async_frame/IAction.h ./include/spp_incl/.
	@cp ../async_frame/ActionSet.h ./include/spp_incl/.
	@cp ../async_frame/ActionInfo.h ./include/spp_incl/.
	@cp ../async_frame/NonStateActionInfo.h ./include/spp_incl/.
	@cp ../async_frame/StateActionInfo.h ./include/spp_incl/.
	@cp ../async_frame/AntiParalActionInfo.h ./include/spp_incl/.
	@cp ../async_frame/MsgBase.h ./include/spp_incl/.
	@cp ../async_frame/PtrMgr.h ./include/spp_incl/.
	@cp ../async_frame/SEXInterface.h ./include/spp_incl/.
	@cp ../comm/stat_mgr/ICostStat.h ./include/spp_incl/.
	@rm ./include/sync_incl -rf
	@-mkdir ./include/sync_incl
	@cp ../sync_frame/include/* ./include/sync_incl/.
