// Code generated by protoc-gen-go.
// source: push_interface.proto
// DO NOT EDIT!

/*
Package ams_act_con is a generated protocol buffer package.

It is generated from these files:
	push_interface.proto

It has these top-level messages:
	CmdBase
*/
package ams_act_con

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CmdBase struct {
	SeqId            *int64 `protobuf:"varint,1,opt,name=seq_id" json:"seq_id,omitempty"`
	CmdId            *int64 `protobuf:"varint,2,opt,name=cmd_id" json:"cmd_id,omitempty"`
	Type             *int64 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	FromIp           []byte `protobuf:"bytes,4,opt,name=from_ip" json:"from_ip,omitempty"`
	ProcessId        *int64 `protobuf:"varint,5,opt,name=process_id" json:"process_id,omitempty"`
	ModId            *int64 `protobuf:"varint,6,opt,name=mod_id" json:"mod_id,omitempty"`
	Version          []byte `protobuf:"bytes,8,opt,name=version" json:"version,omitempty"`
	Body             []byte `protobuf:"bytes,7,opt,name=body" json:"body,omitempty"`
	AppId            []byte `protobuf:"bytes,9,opt,name=app_id" json:"app_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CmdBase) Reset()                    { *m = CmdBase{} }
func (m *CmdBase) String() string            { return proto.CompactTextString(m) }
func (*CmdBase) ProtoMessage()               {}
func (*CmdBase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CmdBase) GetSeqId() int64 {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return 0
}

func (m *CmdBase) GetCmdId() int64 {
	if m != nil && m.CmdId != nil {
		return *m.CmdId
	}
	return 0
}

func (m *CmdBase) GetType() int64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CmdBase) GetFromIp() []byte {
	if m != nil {
		return m.FromIp
	}
	return nil
}

func (m *CmdBase) GetProcessId() int64 {
	if m != nil && m.ProcessId != nil {
		return *m.ProcessId
	}
	return 0
}

func (m *CmdBase) GetModId() int64 {
	if m != nil && m.ModId != nil {
		return *m.ModId
	}
	return 0
}

func (m *CmdBase) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *CmdBase) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *CmdBase) GetAppId() []byte {
	if m != nil {
		return m.AppId
	}
	return nil
}

func init() {
	proto.RegisterType((*CmdBase)(nil), "ams_act_con.CmdBase")
}

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8d, 0xb1, 0x4e, 0xc4, 0x30,
	0x0c, 0x86, 0x55, 0xee, 0xda, 0x72, 0x81, 0x29, 0x02, 0x91, 0x05, 0xe9, 0xc4, 0x74, 0x13, 0x0f,
	0x01, 0x53, 0xd7, 0x7b, 0x81, 0x28, 0xc4, 0x3e, 0xd1, 0x21, 0xb5, 0x2f, 0x0e, 0x48, 0x7d, 0x5a,
	0x5e, 0x05, 0xd9, 0x85, 0xcd, 0xff, 0x27, 0xf9, 0xfb, 0xdc, 0x03, 0x7f, 0xc9, 0x67, 0x9c, 0x97,
	0x86, 0xf5, 0x92, 0x32, 0xbe, 0x72, 0xa5, 0x46, 0xfe, 0x2e, 0x15, 0x89, 0x29, 0xb7, 0x98, 0x69,
	0x79, 0xf9, 0xe9, 0xdc, 0xf8, 0x5e, 0xe0, 0x2d, 0x09, 0xfa, 0x47, 0x37, 0x08, 0x5e, 0xe3, 0x0c,
	0xa1, 0x3b, 0x76, 0xa7, 0xdd, 0xb9, 0x17, 0xbc, 0x4e, 0xa0, 0x38, 0x17, 0x50, 0x7c, 0xb3, 0xe1,
	0x5c, 0x60, 0x02, 0xef, 0xdd, 0xbe, 0xad, 0x8c, 0x61, 0x67, 0xd0, 0x6e, 0xff, 0xe4, 0xc6, 0x4b,
	0xa5, 0x12, 0x67, 0x0e, 0xfb, 0x63, 0x77, 0xba, 0x3f, 0x0f, 0x3a, 0x27, 0xf6, 0xcf, 0xce, 0x71,
	0xa5, 0x8c, 0x22, 0xea, 0xe9, 0xed, 0xe5, 0xf0, 0x47, 0xb6, 0x44, 0x21, 0x4b, 0x0c, 0x5b, 0xa2,
	0x90, 0x26, 0x82, 0x1b, 0xbf, 0xb1, 0xca, 0x4c, 0x4b, 0xb8, 0x35, 0xdd, 0xff, 0xd4, 0xf8, 0x07,
	0xc1, 0x1a, 0x46, 0xc3, 0x76, 0xab, 0x24, 0x31, 0xab, 0xe4, 0x60, 0xb4, 0x4f, 0xcc, 0x13, 0xfc,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x59, 0xb7, 0x90, 0x05, 0x01, 0x00, 0x00,
}
